apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-hq-ingress
  namespace: elasticsearch
spec:
  ingressClassName: traefik
  rules:
    - host: hq.dev-exploravis.mywire.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-hq
                port:
                  number: 5000
