apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hq-strip-prefix
  namespace: elasticsearch
spec:
  stripPrefix:
    prefixes:
      - /hq
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-hq-ingress
  namespace: elasticsearch
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: elasticsearch-hq/hq-strip-prefix
spec:
  rules:
    - host: staging.exploravis.mywire.org
      http:
        paths:
          - path: /hq
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-hq
                port:
                  number: 5000
