apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elasticsearch
helmCharts:
  - name: elasticsearch
    version: 8.11.3
    repo: https://helm.elastic.co
    releaseName: elastic/elasticsearch
    valuesFile: values.yaml
