apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elasticsearch
helmCharts:
  - name: elasticsearch
    repo: https://helm.elastic.co
    releaseName: elasticsearch
    valuesFile: values.yaml
resources:
  - elasticsearch-hq-deployment.yaml
  - elasticsearch-hq-svc.yaml
  # - hq-ingress.yaml
