statefulset:
  replicas: 1

storage:
  persistentVolume:
    enabled: true
    size: 2Gi

tls:
  enabled: true

listeners:
  admin:
    tls:
      enabled: false
    external:
      default:
        tls:
          enabled: false

  kafka:
    tls:
      enabled: false
    external:
      default:
        tls:
          enabled: false

  rpc:
    tls:
      enabled: false

  schemaRegistry:
    enabled: false   
    tls:
      enabled: false
    external:
      default:
        tls:
          enabled: false

console:
  config:
    kafka:
      brokers:
        - "redpanda-0.redpanda.kafka.svc.cluster.local:9093"
  http:
    tls:
      enabled: false
    external:
      default:
        tls:
          enabled: false
    enabled: false   # optional if you don't need PandaProxy
