apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka
helmCharts:
  - name: bitnami
    repo: https://charts.bitnami.com/bitnami                                                                         
    releaseName: kafka
    valuesFile: kafka-values.yaml

