apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka
helmCharts:
  - name: redpanda 
    repo: https://charts.redpanda.com
    releaseName: redpanda 
    valuesFile: kafka-values.yaml

