apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring 


helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    valuesFile: prometheus-values.yaml

  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    valuesFile: grafana-values.yaml

resources:
  - prometheus-ingress.yaml
  - grafana-ingress.yaml
