global:
  deploymentMode: SingleBinary
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
loki:
  auth_enabled: false

test:
  enabled: false

singleBinary:
  enabled: true

ingester:
  wal:
    enabled: true

storage:
  type: filesystem

persistence:
  enabled: true
  size: 10Gi
