apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik
resources:
  - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
helmCharts:
  - name: traefik
    version: 37.2.0
    repo: https://traefik.github.io/charts  
    releaseName: traefik
    valuesFile: values.yaml
    valuesInline:
      installCRDs: true
