apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: staging.exploravis.mywire.org
      http:
        paths:
          - path: /dump-test
            pathType: Prefix
            backend:
              service:
                name: test-ingress
                port:
                  number: 80
